/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rdb.h"
#define DATABASE "personnel.dat" /* '%' passes it through */

bool_t
xdr_record (XDR *xdrs, record *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->firstName, MAX_STR))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->middleInitial, MAX_STR))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->lastName, MAX_STR))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->phone))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->location, MAX_STR))
		 return FALSE;
	return TRUE;
}
